-- Auto-generated by Wallbash for Neovim (LazyVim compatible)

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.g.colors_name = "wallbash"

local colors = {
  bg = "#1C0725",
  fg = "#FFFFFF",
  bg2 = "#4A1442",
  fg2 = "#FFFFFF",
  bg3 = "#9154A0",
  fg3 = "#FAFAFA",
  accent1 = "#DBAAF0",
  accent2 = "#F0AAE5",
  accent3 = "#E2AAF0",
  accent4 = "#F0EAAA",
  error = "#F0CCFF",
  warn = "#F5CCFF",
  info = "#FFCCF7",
  hint = "#FFFBCC",
}

local hl = vim.api.nvim_set_hl

-- Base highlights
hl(0, "Normal", { bg = colors.bg, fg = colors.fg })
hl(0, "NormalFloat", { bg = colors.bg2, fg = colors.fg2 })
hl(0, "Comment", { fg = colors.bg3, italic = true })
hl(0, "Keyword", { fg = colors.accent1, bold = true })
hl(0, "Function", { fg = colors.accent3 })
hl(0, "String", { fg = colors.accent4 })
hl(0, "Number", { fg = colors.accent4 })
hl(0, "Type", { fg = colors.accent2 })
hl(0, "Identifier", { fg = colors.fg })
hl(0, "Statement", { fg = colors.accent1 })
hl(0, "Constant", { fg = colors.accent4 })
hl(0, "Operator", { fg = colors.accent3 })
hl(0, "PreProc", { fg = colors.accent1 })

-- Treesitter highlights
hl(0, "@comment", { link = "Comment" })
hl(0, "@keyword", { link = "Keyword" })
hl(0, "@function", { link = "Function" })
hl(0, "@string", { link = "String" })
hl(0, "@variable", { link = "Identifier" })
hl(0, "@type", { link = "Type" })
hl(0, "@constant", { link = "Constant" })
hl(0, "@operator", { link = "Operator" })
hl(0, "@property", { fg = colors.accent2 })
hl(0, "@parameter", { fg = colors.accent3 })
hl(0, "@tag", { fg = colors.accent1 })
hl(0, "@tag.attribute", { fg = colors.accent2 })

-- UI elements
hl(0, "LineNr", { fg = colors.bg3 })
hl(0, "CursorLine", { bg = colors.bg2 })
hl(0, "CursorLineNr", { fg = colors.accent1, bold = true })
hl(0, "ColorColumn", { bg = colors.bg2 })
hl(0, "SignColumn", { bg = colors.bg })
hl(0, "VertSplit", { fg = colors.bg3 })
hl(0, "StatusLine", { bg = colors.bg2, fg = colors.fg2 })
hl(0, "StatusLineNC", { bg = colors.bg, fg = colors.bg3 })
hl(0, "Pmenu", { bg = colors.bg2, fg = colors.fg2 })
hl(0, "PmenuSel", { bg = colors.bg3, fg = colors.fg3 })
hl(0, "Search", { bg = colors.accent3, fg = colors.bg })
hl(0, "IncSearch", { bg = colors.accent1, fg = colors.bg })
hl(0, "Visual", { bg = colors.bg3 })

-- LSP Diagnostics
hl(0, "DiagnosticError", { fg = colors.error })
hl(0, "DiagnosticWarn", { fg = colors.warn })
hl(0, "DiagnosticInfo", { fg = colors.info })
hl(0, "DiagnosticHint", { fg = colors.hint })

-- Cursor and references
hl(0, "Cursor", { bg = colors.fg, fg = colors.bg })
hl(0, "TermCursor", { bg = colors.fg, fg = colors.bg })
hl(0, "LspReferenceText", { bg = colors.bg3 })
hl(0, "LspReferenceRead", { bg = colors.bg3 })
hl(0, "LspReferenceWrite", { bg = colors.bg3 })
hl(0, "MatchParen", { bg = colors.accent3, fg = colors.bg, bold = true })

-- Neo-tree / NvimTree
hl(0, "NeoTreeNormal", { bg = colors.bg, fg = colors.fg })
hl(0, "NeoTreeNormalNC", { bg = colors.bg, fg = colors.fg })
hl(0, "NvimTreeNormal", { bg = colors.bg, fg = colors.fg })
hl(0, "NvimTreeNormalNC", { bg = colors.bg, fg = colors.fg })
